server:
  port: 9000

spring:
  application:
    name: feign-invoker

eureka:
  instance:
    #    配置该服务实例的主机名称
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/


# 使用配置文件设置Ribbon
# Eureka服务器实例名,即应用名
#service-provider:
#  ribbon:
#    指定自定义负载规则类
#    NFLoadBalancerRuleClassName: MyRule
#    指定自定义Ping类(单独使用Ribbon不会触发Ping机制，IPing接口默认实现类DummyPing直接返回true)
#    NFLoadBalancerPingClassName: MyPing
#    指定服务器列表
#    listOfServers: http://localhost:8080/,http://localhost:8081/


# 开启熔断器（Feign是自带断路器的，它没有默认打开）
feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000

